<div>
    <div>
        <div>
            <div>
                <div class="row">
                    <livewire:flash-message.flash-messages />
                    <div class="col-xs-12">
                        <div class="panel">
                            <div class="panel-heading text-center" style="padding-top: 20px">
                                <h5>Dumaguete Wellmade Ventures Inc. - Dumaguete Plant</h5>
                                <h5 class=" "><b>Revenue Generated by Invoice Type</b></h5>
                                <p style="font-size: 10px; line-height: 0.05"><i>{{ $start_date }} - {{ $end_date }}</i></p>
                            </div>
                            <br><br><br><br>                     
                            <div class="panel-body">
                                
                                <div class="col-md-12">    
                                    <div class="btn-group">
                                        <button class="btn btn-primary btn-labeled btn-md" wire:click="addGenerate"  style=" border-radius: 3px; margin-right: 3px"> <i class="fa fa-filter"></i> Generate</button>       
                                        <button class="btn-md btn btn-purple" wire:click="printPdf" style=" border-radius: 3px;" title="Print"> <i class="fa fa-print"></i> Print</button>
                                    </div>
                                </div>                                
                                <br><br><br>
                                <div class="table-responsive">     
                                    <table class="table table-striped table-bordered" cellspacing="0" width="100%" style="font-size:10px; align-text: center;">                                       
                                        <thead class="bg-trans-dark">
                                            <tr>
                                                <th colspan="2"  style="line-height: 0.9; width: 3%;">#</th>
                                                <th colspan="2"  style="line-height:   1; width: 3%; text-align: center;">Inv. No.</th>
                                                <th colspan="2"  style="line-height: 0.9; width: 3%; text-align: center;">Inv Date</th>
                                                <th colspan="2"  style="line-height:   1; width: 2%">JOEAF No.</th>
                                                <th colspan="2"  style="line-height: 0.9; width: 2%;" class="text-center">JOEAF Date</th>
                                                <th colspan="2"  style="line-height: 0.9; width: 2%;" class="text-center">Customer</th>
                                                <th colspan="2"  style="line-height: 0.9; width: 2%;">STSR</th>
                                                <th colspan="2"  style="line-height: 0.9; width: 4%;">Labor</th>
                                                <th colspan="2"  style="line-height: 0.9; width: 4%;">Parts</th>                                              
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @php
                                                $all_labor_total = 0;
                                                $all_part_total = 0;
                                            @endphp
                                            @foreach ($revenue_generated_invoices as $key => $revenue)
                                                <tr>
                                                    <th colspan="2"  style="line-height: 0.9; width: 3%;">{{ ++$key }}</th>
                                                    <th colspan="2"  style="line-height:   1; width: 3%; text-align: center;">
                                                        @if ($revenue->invoice_type_id == 2)
                                                            {{ $revenue->wv_invoice_no ?? '' }}
                                                        @elseif ($revenue->invoice_type_id == 1)
                                                            {{ $revenue->sb_invoice_no ?? '' }}
                                                        @endif
                                                    </th>
                                                    <th colspan="2"  style="line-height: 0.9; width: 3%; text-align: center;">
                                                        {{ date('Y-m-d', strtotime($revenue->date)) }}
                                                    </th>
                                                    <th colspan="2"  style="line-height:   1; width: 2%">{{ $revenue->jobOrder->jo_no ?? '' }}</th>
                                                    <th colspan="2"  style="line-height: 0.9; width: 2%;" class="text-center">{{ date('Y-m-d', strtotime($revenue->jobOrder->date)) }}</th>
                                                    <th colspan="2"  style="line-height: 0.9; width: 2%;" class="text-center">{{ $revenue->jobOrder->clientProfile->name ?? '' }}</th>
                                                    <th colspan="2"  style="line-height: 0.9; width: 2%;">STSR</th>
                                                    @php
                                                        $labor = 0;
                                                        foreach($revenue->jobOrder->WorkOrders as $work_order) {    
                                                            if($work_order->cancel_reason_id == null) {
                                                                $labor += ($work_order->price + $work_order->amount_increase) * $work_order->qty;
                                                                // (($data->price+$data->amount_increase) * $data->qty)
                                                            }
                                                        }
                                                    @endphp
                                                    <th colspan="2"  style="line-height: 0.9; width: 4%; text-align: right;">{{ number_format($labor, 2) }}</th>
                                                    <th colspan="2"  style="line-height: 0.9; width: 4%; text-align: right;">{{ number_format($revenue->jobOrder->part_total, 2) }}</th>
                                                    @php
                                                        $all_labor_total += $labor;
                                                        $all_part_total += $revenue->jobOrder->part_total;
                                                    @endphp
                                                </tr>
                                            @endforeach
                                            <tr>
                                                <th style="line-height: 0.9; width: 2%; text-align: center;" colspan="14">TOTAL</th>
                                                <th style="line-height: 0.9; width: 4%; text-align: right;" colspan="2">{{ number_format($all_labor_total, 2) }}</th>
                                                <th style="line-height: 0.9; width: 4%; text-align: right;" colspan="2">{{ number_format($all_part_total, 2) }}</th>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>    
                            </div>
                            <!--===================================================-->
                            <!--End Data Table-->
                        </div>
                        <!-- The Generate Modal -->
                        <div wire.ignore.self class="modal fade" id="revenueGeneratedInvoiceTypeModel" tabindex="-1" role="dialog" aria-labelledby="revenueGeneratedInvoiceTypeModel" aria-hidden="true" data-backdrop="static" data-keyboard="false">
                            <div class="modal-dialog" style="width: 400px" role="document">
                               <livewire:report.revenue-generated-invoice-type-form />
                            </div>
                        </div>                          
                    </div>
                </div>
            </div>
                @section('custom_script')
                    @include('layouts.scripts.revenue-generated-invoice-type-scripts');
                @endsection
        </div>
        
    </div>
    
</div>
