<div>
    <div class="row">
        <livewire:flash-message.flash-messages />
        <div class="col-xs-12">
            <div class="panel">
                <div class="panel-heading text-center">
                    <h5 style="padding-top:20px; padding-bottom:0; margin-bottom:3px">Wellmade Dumaguete Plant</h5>   
                    <h4 style="padding-top:0; padding-bottom:0; margin-top:3px; margin-bottom:3px" class="text-bold">Job Order Engineering Week-end Report</h4>
                    {{$startDate != null ? date('Y-m-d',strtotime($startDate)) : now()->firstOfMonth()->format("Y-m-d")}} - {{$endDate != null ? date('Y-m-d',strtotime($endDate)) :  now()->format("Y-m-d")}}
                    <h4 style="padding-top:0; padding-bottom:0; margin-top:3px; margin-bottom:3px"  class="text-bold">Revenue Generated by Deduction</h4>                  
                </div>                        
                <br>               
                <!--Data Table-->                           
                <!--===================================================-->
                <div class="panel-body">      
                    <div class="btn-group">                                   
                        <button class="btn btn-primary btn-labeled" wire:click="addGenerate" title="Generate"><i class="btn-label demo-pli-add icon-fw"></i> Generate</button>       
                        <button class="btn btn-purple btn-labeled" wire:click="printPdf" title="Print"> <i class="btn-label fa fa-print"></i> Print</button>                                  
                    </div>                      
                    <br><br>
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered" cellspacing="0" width="100%" style="font-size:10px">      
                            <thead>
                                <tr class="bg-trans-dark">
                                    <th rowspan="2" style="text-align:center">Date</th>
                                    <th rowspan="2" style="text-align:center">Parts Total</th>
                                    <th rowspan="2" style="text-align:center">ER Total</th>
                                    <th colspan="3" style="text-align:center">Grinding</th>
                                    <th colspan="3" style="text-align:center">Boring/Horing</th>
                                    <th colspan="2" style="text-align:center">Refacing</th>
                                    <th colspan="2" style="text-align:center">Engine Rebuild</th>
                                    <th rowspan="2" style="text-align:center">MF Total</th>
                                    <th colspan="7" style="text-align:center">Machining</th>
                                    <th colspan="2" style="text-align:center">SP</th>
                                    <th rowspan="2" style="text-align:center">Calib Total</th>
                                    <th colspan="3" style="text-align:center">Calibration</th>
                                </tr>   
                                <tr class="bg-trans-dark">
                                    <th style="text-align:center">Cshaft</th>
                                    <th style="text-align:center">Surface</th>
                                    <th style="text-align:center">Valve</th>
                                    <th style="text-align:center">Liners</th>
                                    <th style="text-align:center">Mhouse</th>
                                    <th style="text-align:center">Conrod</th>
                                    <th style="text-align:center">Vseat</th>
                                    <th style="text-align:center">Lathe</th>
                                    <th style="text-align:center">Tig</th>
                                    <th style="text-align:center">Labor</th>
                                    <th style="text-align:center">Lathe</th>
                                    <th style="text-align:center">Weld</th>
                                    <th style="text-align:center">Mill</th>
                                    <th style="text-align:center">Shaper</th>
                                    <th style="text-align:center">Bal</th>
                                    <th style="text-align:center">Labor</th>
                                    <th style="text-align:center">Bmill</th>
                                    <th style="text-align:center">Bore</th>
                                    <th style="text-align:center">KMill</th>
                                    <th style="text-align:center">Pump</th>
                                    <th style="text-align:center">Inject</th>
                                    <th style="text-align:center">Cparts</th>
                                </tr>                           
                            </thead>
                            <tbody>
                              
                                @php
                                    //grandtotal
                                    $er_parts_grand_total = 0;
                                    $er_grand_total = 0;
                                    $er_cshaft_grand_total = 0;       
                                    $er_surface_grand_total = 0;
                                    $er_valve_grand_total = 0;
                                    $er_liners_grand_total = 0;
                                    $er_mhouse_grand_total = 0;
                                    $er_conrod_grand_total = 0;
                                    $er_vseat_grand_total = 0;
                                    $er_lathe_grand_total = 0;
                                    $er_labor_grand_total = 0;
                                    $mf_grand_total = 0;
                                    $mf_lathe_grand_total = 0;
                                    $mf_weld_grand_total = 0;
                                    $mf_mill_grand_total = 0;
                                    $mf_shaper_grand_total = 0;
                                    $mf_bal_grand_total = 0;
                                    $mf_labor_grand_total = 0;
                                    $mf_bmill_grand_total = 0;
                                    $mf_bore_grand_total = 0;
                                    $mf_kmill_grand_total = 0;
                                    $calib_grand_total = 0;
                                    $calib_inject_grand_total = 0;
                                    $calib_pump_grand_total = 0;
                                    $part_overall_total = 0;
                                @endphp
                                {{-- @dd($transaction_summarry) --}}
                                @foreach($transaction_summarry as $key => $value)
                              
                                <tr>
                                    <td style="text-align:center">{{ $key }}</td>
                                @php
                                    $er_total = 0;
                                    $cshaft = 0;
                                    $er_cs_labor = 0;
                                    $er_cb_lathe = 0;
                                    $er_liners = 0;
                                    $er_mhouse = 0;
                                    $er_cb_labor = 0;
                                    $er_ca_milling = 0;
                                    $er_cb_surface = 0;
                                    $er_ca_labor = 0;
                                    $er_conrod = 0;
                                    $er_valve = 0;
                                    $er_cha_lathe = 0;
                                    $er_cha_surface = 0;
                                    $er_vseat = 0;
                                    $er_cha_labor = 0;
                                    $er_mc_milling = 0;
                                    $mf_total = 0;
                                    $mf_lathe = 0;
                                    $mf_weld = 0;
                                    $mf_mill = 0;
                                    $mf_shaper = 0;
                                    $mf_bal = 0;
                                    $mf_labor = 0;
                                    $mf_bmill = 0;
                                    $mf_bore = 0;
                                    $mf_kmill = 0;
                                    $calibTotal = 0;
                                    $calib_inject = 0;
                                    $calib_pump = 0;
    
                                    $all_er_surface = 0;        
                                    $all_er_labor = 0;      
                                    $all_er_lathe = 0;     
                                    $all_er_milling =0;           
                                    $partTotal = 0;
                                @endphp
                                @foreach($value as $data)
                          
                                    @php

                                    foreach($data->jobOrder->workOrders as $work_order) {    
                                        if($work_order->job_type_id == 2) {
                                            if($work_order->er_work_group_id == 3 && $work_order->er_work_sub_type_id == 28) {
                                                if($work_order->max_discount != null){
                                                    $cshaft += (($work_order->price + $work_order->amount_increase)*$work_order->qty) - ((($work_order->price + $work_order->amount_increase)*$work_order->qty) * ($work_order->max_discount/100));
                                                }else{
                                                    $cshaft += ($work_order->price + $work_order->amount_increase)*$work_order->qty;
                                                }
                                            }elseif($work_order->er_work_group_id == 3 && $work_order->er_work_sub_type_id == 35) {
                                                if($work_order->max_discount != null){
                                                    $er_cs_labor += (($work_order->price + $work_order->amount_increase)*$work_order->qty) - ((($work_order->price + $work_order->amount_increase)*$work_order->qty) * ($work_order->max_discount/100));
                                                }else{
                                                    $er_cs_labor +=  ($work_order->price + $work_order->amount_increase)*$work_order->qty;
                                                }
                                            }
                                            if($work_order->er_work_group_id == 4 && $work_order->er_work_sub_type_id == 20) {
                                                if($work_order->max_discount != null){
                                                    $er_cb_lathe += (($work_order->price + $work_order->amount_increase)*$work_order->qty) - ((($work_order->price + $work_order->amount_increase)*$work_order->qty) * ($work_order->max_discount/100));
                                                }else{
                                                    $er_cb_lathe +=  ($work_order->price + $work_order->amount_increase)*$work_order->qty;
                                                }
                                            }elseif($work_order->er_work_group_id == 4 && $work_order->er_work_sub_type_id == 32) {
                                                if($work_order->max_discount != null){
                                                    $er_liners += (($work_order->price + $work_order->amount_increase)*$work_order->qty) - ((($work_order->price + $work_order->amount_increase)*$work_order->qty) * ($work_order->max_discount/100));
                                                }else{
                                                    $er_liners +=  ($work_order->price + $work_order->amount_increase)*$work_order->qty;
                                                }
                                            }elseif($work_order->er_work_group_id == 4 && $work_order->er_work_sub_type_id == 33) {
                                                if($work_order->max_discount != null){
                                                    $er_mhouse += (($work_order->price + $work_order->amount_increase)*$work_order->qty) - ((($work_order->price + $work_order->amount_increase)*$work_order->qty) * ($work_order->max_discount/100));
                                                }else{
                                                    $er_mhouse +=  ($work_order->price + $work_order->amount_increase)*$work_order->qty;
                                                }
                                            }elseif($work_order->er_work_group_id == 4 && $work_order->er_work_sub_type_id == 34) {
                                                if($work_order->max_discount != null){
                                                    $er_cb_labor += (($work_order->price + $work_order->amount_increase)*$work_order->qty) - ((($work_order->price + $work_order->amount_increase)*$work_order->qty) * ($work_order->max_discount/100));
                                                }else{
                                                    $er_cb_labor +=  ($work_order->price + $work_order->amount_increase)*$work_order->qty;
                                                }
                                            }elseif($work_order->er_work_group_id == 4 && $work_order->er_work_sub_type_id == 38) {
                                                //add all surfaceif same day
                                                if($work_order->max_discount != null){
                                                    $er_cb_surface += (($work_order->price + $work_order->amount_increase)*$work_order->qty) - ((($work_order->price + $work_order->amount_increase)*$work_order->qty) * ($work_order->max_discount/100));
                                                }else{
                                                    $er_cb_surface +=  ($work_order->price + $work_order->amount_increase)*$work_order->qty;
                                                }
                                            }
                                            if($work_order->er_work_group_id == 5 && $work_order->er_work_sub_type_id == 21) {
                                                if($work_order->max_discount != null){
                                                    $er_ca_milling += (($work_order->price + $work_order->amount_increase)*$work_order->qty) - ((($work_order->price + $work_order->amount_increase)*$work_order->qty) * ($work_order->max_discount/100));
                                                }else{
                                                    $er_ca_milling +=  ($work_order->price + $work_order->amount_increase)*$work_order->qty;
                                                }
                                            }elseif($work_order->er_work_group_id == 5 && $work_order->er_work_sub_type_id == 36) {
                                                if($work_order->max_discount != null){
                                                    $er_ca_labor += (($work_order->price + $work_order->amount_increase)*$work_order->qty) - ((($work_order->price + $work_order->amount_increase)*$work_order->qty) * ($work_order->max_discount/100));
                                                }else{
                                                    $er_ca_labor +=  ($work_order->price + $work_order->amount_increase)*$work_order->qty;
                                                }
                                            }elseif($work_order->er_work_group_id == 5 && $work_order->er_work_sub_type_id == 37) {
                                                if($work_order->max_discount != null){
                                                    $er_conrod += (($work_order->price + $work_order->amount_increase)*$work_order->qty) - ((($work_order->price + $work_order->amount_increase)*$work_order->qty) * ($work_order->max_discount/100));
                                                }else{
                                                    $er_conrod +=  ($work_order->price + $work_order->amount_increase)*$work_order->qty;
                                                }
                                            }
                                            if($work_order->er_work_group_id == 6 && $work_order->er_work_sub_type_id == 19) {
                                                if($work_order->max_discount != null){
                                                    $er_valve += (($work_order->price + $work_order->amount_increase)*$work_order->qty) - ((($work_order->price + $work_order->amount_increase)*$work_order->qty) * ($work_order->max_discount/100));
                                                }else{
                                                    $er_valve +=  ($work_order->price + $work_order->amount_increase)*$work_order->qty;
                                                }
                                            }elseif($work_order->er_work_group_id == 6 && $work_order->er_work_sub_type_id == 22) {
                                                if($work_order->max_discount != null){
                                                    $er_cha_lathe += (($work_order->price + $work_order->amount_increase)*$work_order->qty) - ((($work_order->price + $work_order->amount_increase)*$work_order->qty) * ($work_order->max_discount/100));
                                                }else{
                                                    $er_cha_lathe +=  ($work_order->price + $work_order->amount_increase)*$work_order->qty;
                                                }
                                            }elseif($work_order->er_work_group_id == 6 && $work_order->er_work_sub_type_id == 29) {
                                                    if($work_order->max_discount != null){
                                                        $er_cha_surface += (($work_order->price + $work_order->amount_increase)*$work_order->qty) - ((($work_order->price + $work_order->amount_increase)*$work_order->qty) * ($work_order->max_discount/100));
                                                    }else{
                                                        $er_cha_surface +=  ($work_order->price + $work_order->amount_increase)*$work_order->qty;
                                                    }
                                            }elseif($work_order->er_work_group_id == 6 && $work_order->er_work_sub_type_id == 30) {
                                                    if($work_order->max_discount != null){
                                                        $er_vseat += (($work_order->price + $work_order->amount_increase)*$work_order->qty) - ((($work_order->price + $work_order->amount_increase)*$work_order->qty) * ($work_order->max_discount/100));
                                                    }else{
                                                        $er_vseat +=  ($work_order->price + $work_order->amount_increase)*$work_order->qty;
                                                    }
                                            }elseif($work_order->er_work_group_id == 6 && $work_order->er_work_sub_type_id == 31) {
                                                    if($work_order->max_discount != null){
                                                        $er_cha_labor += (($work_order->price + $work_order->amount_increase)*$work_order->qty) - ((($work_order->price + $work_order->amount_increase)*$work_order->qty) * ($work_order->max_discount/100));
                                                    }else{
                                                        $er_cha_labor +=  ($work_order->price + $work_order->amount_increase)*$work_order->qty;
                                                    }
                                            }
                                            if($work_order->er_work_group_id == 7 && $work_order->er_work_sub_type_id == 23) {
                                                    if($work_order->max_discount != null){
                                                        $er_mc_milling += (($work_order->price + $work_order->amount_increase)*$work_order->qty) - ((($work_order->price + $work_order->amount_increase)*$work_order->qty) * ($work_order->max_discount/100));
                                                    }else{
                                                        $er_mc_milling +=  ($work_order->price + $work_order->amount_increase)*$work_order->qty;
                                                    }
                                            }
                                            $all_er_labor = $er_cs_labor+$er_cb_labor+$er_ca_labor+$er_cha_labor;
                                            $all_er_lathe = $er_cb_lathe+$er_cha_lathe;
                                            $all_er_surface = $er_cb_surface+$er_cha_surface;
                                            $all_er_milling = $er_ca_milling+$er_mc_milling;
                                            $er_total =  $all_er_labor+$all_er_lathe+$all_er_surface+$all_er_milling+$cshaft+$er_liners+$er_mhouse+$er_conrod+$er_valve+$er_vseat; 

                                         //mf
                                        }elseif($work_order->job_type_id == 1) {
                                            if(($work_order->mf_work_group_id == 1 || $work_order->mf_work_group_id == 1) && $work_order->mf_work_sub_type_id == 1) {
                                                if($work_order->max_discount != null){
                                                    $mf_lathe += ((($work_order->price + $work_order->amount_increase)*$work_order->qty) - ((($work_order->price + $work_order->amount_increase)*$work_order->qty) * ($work_order->max_discount/100)));
                                                }else{
                                                    $mf_lathe +=  ($work_order->price + $work_order->amount_increase)*$work_order->qty;
                                                }
                                            }elseif(($work_order->mf_work_group_id == 1 || $work_order->mf_work_group_id == 2) && $work_order->mf_work_sub_type_id == 2) {
                                                if($work_order->max_discount != null){
                                                    $mf_weld += ((($work_order->price + $work_order->amount_increase)*$work_order->qty) - ((($work_order->price + $work_order->amount_increase)*$work_order->qty) * ($work_order->max_discount/100)));
                                                }else{
                                                    $mf_weld +=  ($work_order->price + $work_order->amount_increase)*$work_order->qty;
                                                }
                                            }elseif(($work_order->mf_work_group_id == 1 || $work_order->mf_work_group_id == 2) && $work_order->mf_work_sub_type_id == 3) {
                                                if($work_order->max_discount != null){
                                                    $mf_mill += ((($work_order->price + $work_order->amount_increase)*$work_order->qty) - ((($work_order->price + $work_order->amount_increase)*$work_order->qty) * ($work_order->max_discount/100)));
                                                }else{
                                                    $mf_mill +=  ($work_order->price + $work_order->amount_increase)*$work_order->qty;
                                                }
                                            }elseif(($work_order->mf_work_group_id == 1 || $work_order->mf_work_group_id == 2) && $work_order->mf_work_sub_type_id == 4) {
                                                if($work_order->max_discount != null){
                                                    $mf_shaper += ((($work_order->price + $work_order->amount_increase)*$work_order->qty) - ((($work_order->price + $work_order->amount_increase)*$work_order->qty) * ($work_order->max_discount/100)));
                                                }else{
                                                    $mf_shaper +=  ($work_order->price + $work_order->amount_increase)*$work_order->qty;
                                                }
                                            }elseif(($work_order->mf_work_group_id == 1 || $work_order->mf_work_group_id == 2) && $work_order->mf_work_sub_type_id == 5) {
                                                if($work_order->max_discount != null){
                                                    $mf_bal += ((($work_order->price + $work_order->amount_increase)*$work_order->qty) - ((($work_order->price + $work_order->amount_increase)*$work_order->qty) * ($work_order->max_discount/100)));
                                                }else{
                                                    $mf_bal +=  ($work_order->price + $work_order->amount_increase)*$work_order->qty;
                                                }
                                            }elseif(($work_order->mf_work_group_id == 1 || $work_order->mf_work_group_id == 2) && $work_order->mf_work_sub_type_id == 6) {
                                                if($work_order->max_discount != null){
                                                    $mf_labor += ((($work_order->price + $work_order->amount_increase)*$work_order->qty) - ((($work_order->price + $work_order->amount_increase)*$work_order->qty) * ($work_order->max_discount/100)));
                                                }else{
                                                    $mf_labor +=  ($work_order->price + $work_order->amount_increase)*$work_order->qty;
                                                }
                                            }elseif(($work_order->mf_work_group_id == 1 || $work_order->mf_work_group_id == 2) && $work_order->mf_work_sub_type_id == 7) {
                                                if($work_order->max_discount != null){
                                                    $mf_bmill += ((($work_order->price + $work_order->amount_increase)*$work_order->qty) - ((($work_order->price + $work_order->amount_increase)*$work_order->qty) * ($work_order->max_discount/100)));
                                                }else{
                                                    $mf_bmill +=  ($work_order->price + $work_order->amount_increase)*$work_order->qty;
                                                }
                                            }elseif(($work_order->mf_work_group_id == 1 || $work_order->mf_work_group_id == 2) && $work_order->mf_work_sub_type_id == 8) {
                                                if($work_order->max_discount != null){
                                                    $mf_bore += ((($work_order->price + $work_order->amount_increase)*$work_order->qty) - ((($work_order->price + $work_order->amount_increase)*$work_order->qty) * ($work_order->max_discount/100)));
                                                }else{
                                                    $mf_bore +=  ($work_order->price + $work_order->amount_increase)*$work_order->qty;
                                                }
                                            }elseif(($work_order->mf_work_group_id == 1 || $work_order->mf_work_group_id == 2) && $work_order->mf_work_sub_type_id == 9) {
                                                if($work_order->max_discount != null){
                                                    $mf_kmill += ((($work_order->price + $work_order->amount_increase)*$work_order->qty) - ((($work_order->price + $work_order->amount_increase)*$work_order->qty) * ($work_order->max_discount/100)));
                                                }else{
                                                    $mf_kmill +=  ($work_order->price + $work_order->amount_increase)*$work_order->qty;
                                                }
                                            }
                                            $mf_total = $mf_lathe+$mf_weld+$mf_mill+$mf_shaper+$mf_bal+$mf_labor+$mf_bmill+$mf_bore+$mf_kmill;
                                            
                                       // calib
                                        }elseif($work_order->job_type_id == 3) {
                                            if($work_order->calib_work_group_id == 8 && $work_order->calib_work_sub_type_id == 26) {
                                                if($work_order->max_discount != null){
                                                    $calib_inject += (($work_order->price + $work_order->amount_increase)*$work_order->qty) - ((($work_order->price + $work_order->amount_increase)*$work_order->qty) * ($work_order->max_discount/100));
                                                }else{
                                                    $calib_inject +=  ($work_order->price + $work_order->amount_increase)*$work_order->qty;
                                                }
                                           }elseif($work_order->calib_work_group_id == 8 && $work_order->calib_work_sub_type_id == 27) {
                                                if($work_order->max_discount != null){
                                                    $calib_pump += (($work_order->price + $work_order->amount_increase)*$work_order->qty) - ((($work_order->price + $work_order->amount_increase)*$work_order->qty) * ($work_order->max_discount/100));
                                                }else{
                                                    $calib_pump +=  ($work_order->price + $work_order->amount_increase)*$work_order->qty;
                                                }
                                           }
                                           $calibTotal = $calib_inject+$calib_pump;
                                       }  
                                    }  
                                    
                                    if($data->jobOrder->part_total != null) {
                                        $partTotal += $data->jobOrder->part_total;
                                    }   
                                    @endphp

                                @endforeach
                                    <td style="text-align:right; border-right: hidden">{{ number_format($partTotal) }}</td>
                                    <td style="text-align:right; border-right: hidden">{{ number_format($er_total) ?? 0 }}</td>
                                    <td style="text-align:right; border-right: hidden">{{ number_format($cshaft) ?? 0}}</td>
                                    <td style="text-align:right; border-right: hidden">{{ number_format($all_er_surface) ?? 0}}</td>
                                    <td style="text-align:right; border-right: hidden">{{ number_format($er_valve) ?? 0}}</td>
                                    <td style="text-align:right; border-right: hidden">{{ number_format($er_liners) ?? 0}}</td>
                                    <td style="text-align:right; border-right: hidden">{{ number_format($er_mhouse) ?? 0}}</td>
                                    <td style="text-align:right; border-right: hidden">{{ number_format($er_conrod) ?? 0}}</td>
                                    <td style="text-align:right; border-right: hidden">{{ number_format($er_vseat) ?? 0}}</td>
                                    <td style="text-align:right; border-right: hidden">{{ number_format($all_er_lathe) ?? 0}}</td>
                                    <td style="text-align:right; border-right: hidden">{{ 0 }}</td> <!--not exist-->
                                    <td style="text-align:right; border-right: hidden">{{ number_format($all_er_labor) ?? 0 }}</td>
                                    <td style="text-align:right; border-right: hidden">{{ number_format($mf_total) ?? 0 }}</td>
                                    <td style="text-align:right; border-right: hidden">{{ number_format($mf_lathe) ?? 0 }}</td>
                                    <td style="text-align:right; border-right: hidden">{{ number_format($mf_weld) ?? 0}}</td>
                                    <td style="text-align:right; border-right: hidden">{{ number_format($mf_mill) ?? 0}}</td>
                                    <td style="text-align:right; border-right: hidden">{{ number_format($mf_shaper) ?? 0}}</td>
                                    <td style="text-align:right; border-right: hidden">{{ number_format($mf_bal) ?? 0}}</td>
                                    <td style="text-align:right; border-right: hidden">{{ number_format($mf_labor) ?? 0}}</td>
                                    <td style="text-align:right; border-right: hidden">{{ number_format($mf_bmill) ?? 0}}</td>
                                    <td style="text-align:right; border-right: hidden">{{ number_format($mf_bore) ?? 0}}</td>
                                    <td style="text-align:right; border-right: hidden">{{ number_format($mf_kmill) ?? 0}}</td>
                                    <td style="text-align:right; border-right: hidden">{{ number_format($calibTotal) ?? 0}}</td>
                                    <td style="text-align:right; border-right: hidden">{{ number_format($calib_inject) ?? 0}}</td>
                                    <td style="text-align:right; border-right: hidden">{{ number_format($calib_pump) ?? 0}}</td>
                                    <td style="text-align:right">0</td> <!--not exist-->
                                  
                                    @php
                                        if($data->jobOrder->part_total != null) {
                                            $part_overall_total += $partTotal;
                                        }   
                                    @endphp
                                </tr>
                                @php
                                // GRAND TOTAL
                                      $er_parts_grand_total += $partTotal;
                                      $er_grand_total += $er_total;
                                      $er_cshaft_grand_total += $cshaft;       
                                      $er_surface_grand_total += $all_er_surface;
                                      $er_valve_grand_total += $er_valve;
                                      $er_liners_grand_total += $er_liners;
                                      $er_mhouse_grand_total += $er_mhouse;
                                      $er_conrod_grand_total += $er_conrod;
                                      $er_vseat_grand_total += $er_vseat;
                                      $er_lathe_grand_total += $all_er_lathe;
                                      $er_labor_grand_total += $all_er_labor;
                                      $mf_grand_total += $mf_total;
                                      $mf_lathe_grand_total += $mf_lathe;
                                      $mf_weld_grand_total += $mf_weld;
                                      $mf_mill_grand_total += $mf_mill;
                                      $mf_shaper_grand_total += $mf_shaper;
                                      $mf_bal_grand_total += $mf_bal;
                                      $mf_labor_grand_total += $mf_labor;
                                      $mf_bmill_grand_total += $mf_bmill;
                                      $mf_bore_grand_total += $mf_bore;
                                      $mf_kmill_grand_total += $mf_kmill;
                                      $calib_grand_total += $calibTotal;
                                      $calib_inject_grand_total += $calib_inject;
                                      $calib_pump_grand_total += $calib_pump;
                                  @endphp
                                @endforeach
                                <tr>                                 
                                    <td style="font-weight: bold; text-align:center; "> Grand Total: </td>
                                    <td style="font-weight: bold; text-align:right; border-right: hidden">{{ number_format($er_parts_grand_total) ?? 0}}</td>
                                    <td style="font-weight: bold; text-align:right; border-right: hidden">{{ number_format($er_grand_total) ?? 0}}</td>
                                    <td style="font-weight: bold; text-align:right; border-right: hidden">{{ number_format($er_cshaft_grand_total) ?? 0}}</td>
                                    <td style="font-weight: bold; text-align:right; border-right: hidden">{{ number_format($er_surface_grand_total) ?? 0}}</td>
                                    <td style="font-weight: bold; text-align:right; border-right: hidden">{{ number_format($er_valve_grand_total) ?? 0}}</td>
                                    <td style="font-weight: bold; text-align:right; border-right: hidden">{{ number_format($er_liners_grand_total) ?? 0}}</td>
                                    <td style="font-weight: bold; text-align:right; border-right: hidden">{{ number_format($er_mhouse_grand_total) ?? 0}}</td>
                                    <td style="font-weight: bold; text-align:right; border-right: hidden">{{ number_format($er_conrod_grand_total) ?? 0}}</td>
                                    <td style="font-weight: bold; text-align:right; border-right: hidden">{{ number_format($er_vseat_grand_total) ?? 0}}</td>
                                    <td style="font-weight: bold; text-align:right; border-right: hidden">{{ number_format($er_lathe_grand_total) ?? 0}}</td>
                                    <td style="font-weight: bold; text-align:right; border-right: hidden">0</td><!--not exist-->
                                    <td style="font-weight: bold; text-align:right; border-right: hidden">{{ number_format($er_labor_grand_total) ?? 0}}</td>
                                    <td style="font-weight: bold; text-align:right; border-right: hidden">{{ number_format($mf_grand_total) ?? 0}}</td>
                                    <td style="font-weight: bold; text-align:right; border-right: hidden">{{ number_format($mf_lathe_grand_total) ?? 0}}</td>
                                    <td style="font-weight: bold; text-align:right; border-right: hidden">{{ number_format($mf_weld_grand_total) ?? 0}}</td>
                                    <td style="font-weight: bold; text-align:right; border-right: hidden">{{ number_format($mf_mill_grand_total) ?? 0}}</td>
                                    <td style="font-weight: bold; text-align:right; border-right: hidden">{{ number_format($mf_shaper_grand_total) ?? 0}}</td>
                                    <td style="font-weight: bold; text-align:right; border-right: hidden">{{ number_format($mf_bal_grand_total) ?? 0}}</td>
                                    <td style="font-weight: bold; text-align:right; border-right: hidden">{{ number_format($mf_labor_grand_total) ?? 0}}</td>
                                    <td style="font-weight: bold; text-align:right; border-right: hidden">{{ number_format($mf_bmill_grand_total) ?? 0}}</td>
                                    <td style="font-weight: bold; text-align:right; border-right: hidden">{{ number_format($mf_bore_grand_total) ?? 0}}</td>
                                    <td style="font-weight: bold; text-align:right; border-right: hidden">{{ number_format($mf_kmill_grand_total) ?? 0}}</td>
                                    <td style="font-weight: bold; text-align:right; border-right: hidden">{{ number_format($calib_grand_total) ?? 0}}</td>
                                    <td style="font-weight: bold; text-align:right; border-right: hidden">{{ number_format($calib_inject_grand_total) ?? 0}}</td>
                                    <td style="font-weight: bold; text-align:right; border-right: hidden">{{ number_format($calib_pump_grand_total) ?? 0}}</td>
                                    <td style="font-weight: bold; text-align:right">0</td> <!--not exist-->
                                </tr>
                            </tbody>      
                       </table>  
                    </div>    
                </div>
                <!--===================================================-->
                <!--End Data Table-->
            </div>
            <!-- The Generate Modal -->
            <div wire.ignore.self class="modal fade" id="weeklyRevenueGeneratedwithDeductionModal" tabindex="-1" role="dialog" 
            aria-labelledby="weeklyRevenueGeneratedwithDeductionModal" aria-hidden="true" data-backdrop="static" data-keyboard="false">
                <div class="modal-dialog" style="width: 450px" role="document">
                   @include('livewire.report.weekly-revenue-generated-with-deduction-form')
                </div>
            </div>
        </div>
    </div>
</div>
    @section('custom_script')
        @include('layouts.scripts.weekly-revenue-generated-with-deduction');
    @endsection